BOARD_TAG = nano
BOARD_SUB = atmega328old
ARDMK_VENDOR = archlinux-arduino
AVRDUDE_CONF = /etc/avrdude.conf
ARDUINO_LIB_PATH = /home/torsten/Arduino/libraries
USER_LIB_PATH = libs
ARDUINO_PORT = /dev/ttyUSB0
ARDUINO_LIBS = RDM6300 SoftwareSerial
CXXFLAGS_STD=-std=c++11

include /usr/share/arduino/Arduino.mk

